config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      put :toggle
      get :following, :followers
    end
  end
  
  
  resources :microposts do
    resources :comments, only: [:create, :destroy]
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :microposts, :has_many => :comments
  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
      
  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
      
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/admin', to: 'static_pages#admin'
  match '/location', to: 'static_pages#location'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
  
  def help
  end

  def about
  end

  def contact
  end
  
  def admin
    @user = User.new
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<div class="center">
<p>
  Hanna Salopaasi
</br>
  0358645
</br>
  hanna.salopaasi@lut.fi
</p>
</div>
<p>
  Harjoitustyö on tehty Ruby on Railsilla.
  Pohjana harjoityössä on käytetty <a href="http://railstutorial.org/">Ruby on Rails Tutoriaalia</a>.
  Toisena apuna on ollut 
  <a href="http://guides.rubyonrails.org/getting_started.html">Getting started with Rails-tutoriaali</a>.
</p>
<p>
  Kaikkia tehtävänannossa vaadittuja ominaisuuksia ei harjoitustyöstä valitettavasti kiinnostuksen
  puutteen takia löydy. 
  
  <ul>
    Puuttuvat ominaisuudet:

    <li>RSS-syöte</li>
    <li>mobiiliasettelu</li>
  </ul>
  <ul>
    Puuttuvat vaihtoehtoiset ominaisuudet:
    <li>offline-selailu</li>
    <li>geo-tagit</li>

  </ul>
  
  Muut vaaditut ominaisuudet löytyvät.
  
</p>
<h3>Admin</h3>
<p>
  Admin ominaisuuden voi kytkeä päälle ainoastaan railsin komentoriviä käyttäen: (User.find(haluttu_id).toggle!(:admin)).
  Valmiina adminina databasessa on admin/123456. Admin voi poistaa ja jäädyttää käyttäjiä käyttäjälistauksesta. Tämän
  lisäksi admin-käyttäjillä näkyy headerin pudotusvalikossa erillinen admin-sivu, josta voi lisätä käyttäjän.
</p>
<h3>Käyttäjä</h3>
<p>
  Esimerkkikäyttäjänä järjestelmässä on sssss/123456. Käyttäjä pystyy tekemään päivityksiä omalta home-sivultaan. Home sivulla myös
  näkyy käyttäjän feed, johon tulee näkymään käyttäjän seuraamien käyttäjien päivitykset. Tämä ei ollut tarkoitettu ominaisuus, mutta
  sen poistaminen osoittautui sen merkitystä monimutkaisemmaksi, joten ominaisuus säilyi. Käyttäjän päivityksiä pystyy kommentoimaan,
  jos käyttäjä, jonka päivitystä haluaa kommentoida, seuraa käyttäjää, joka haluaa kommentoida. 
</p>
<p>
  Käyttäjää luodessa kysytään käyttäjänimi, note ja salasana. Note näkyy käyttäjän profiilisivulla tämän nimen perässä. Se on rajoitettu
  50 merkkiin ja siinä voi kertoa esimerkiksi oikean nimen tai hauskan kommentin itsestään tai mistä tahansa. Note ei ole pakollinen ja
  käyttäjä pystyy muokkaamaan sitä omista asetuksistaan.
</p>
<h3>Päivitykset/kommentit</h3>
<p>
  Käyttäjä pystyy poistamaan päivityksiään ja kommenttejaan.  
</p>
<p>
  Käyttäjä pystyy valitsemaan kenen hän haluaa pystyvän kommentoimaan omia päivityksiään seuraamalla näitä käyttäjiä. Seuraamalla käyttäjää
  et siis pysty automaattisesti kommentoimaan hänen päivityksiään, vaan kyseisen käyttäjän pitää myös seurata sinun päivityksiäsi.</p>
<h3>Kaverilista</h3>
<p>
  Käyttäjän kaverilista eli ketä käyttäjä seuraa näkyy käyttäjän profiilisivulla.
</p>

app/views/static_pages/admin.html.erb
<% provide(:title, 'Help') %>
<h3>Create user</h3>
<div class="row">
  <div class="span6 offset3">
  <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "Username" %>
      <%= f.text_field :name %>

      <%= f.label :note %>
      <%= f.text_field :note %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create User", class: "btn btn-large btn-primary" %>
    <% end %>
  <p>
    To inactivate/activate user and to delete user, see <%= link_to 'Users-page.', users_path %>
  </p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
</p>



app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <div class="span8">
      <h3><%= current_user.name %></h3>
      <%= render 'shared/feed' %>
    </div>
    <aside class="span4">
      <section>
        <h4>
          Make a post
        </h4>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
      <section>
        <%= link_to 'location', location_path %>
      </section>
    </aside>

  </div>
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to Leevitter</h1>

    <%= link_to "Sign up now!", signup_path, 
                                class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/static_pages/location.html.erb
<p id="demo">Click the button to get your position:</p>
<button onclick="getLocation()">Try It</button>
<div id="mapholder"></div>
<script>
var x=document.getElementById("demo");
function getLocation()
  {
  if (navigator.geolocation)
    {
    navigator.geolocation.getCurrentPosition(showPosition,showError);
    }
  else{x.innerHTML="Geolocation is not supported by this browser.";}
  }

function showPosition(position)
  {
  var latlon=position.coords.latitude+","+position.coords.longitude;

  var img_url="http://maps.googleapis.com/maps/api/staticmap?center="
  +latlon+"&zoom=14&size=400x300&sensor=false";
  document.getElementById("mapholder").innerHTML="<img src='"+img_url+"'>";
  }

function showError(error)
  {
  switch(error.code) 
    {
    case error.PERMISSION_DENIED:
      x.innerHTML="User denied the request for Geolocation."
      break;
    case error.POSITION_UNAVAILABLE:
      x.innerHTML="Location information is unavailable."
      break;
    case error.TIMEOUT:
      x.innerHTML="The request to get user location timed out."
      break;
    case error.UNKNOWN_ERROR:
      x.innerHTML="An unknown error occurred."
      break;
    }
  }
</script>